# Generated by Django 6.1.1 on 2026-09-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_remove_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.BooleanField(default=False),
        ),
    ]
