# Generated by Django 6.1.1 on 2026-09-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
